[package]
name = "binsider"
version = "0.1.0"
description = "Analyze ELF binaries like a boss"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
repository = "https://github.com/orhun/binsider"
edition = "2021"

[dependencies]
ratatui = "0.26.1"
crossterm = "0.27.0"
clap = { version = "4.4.2", features = ["derive", "env", "wrap_help", "cargo"] }
thiserror = "1.0.48"
elf = "0.7.1"
rust-strings = "0.4.0"
heh = "0.5.0"
tui-input = "0.8.0"
tui-popup = "0.2.4"
unicode-width = "0.1.11"
textwrap = "0.16.1"
lurk-cli = { git = "https://github.com/orhun/lurk", branch = "feat/improve_lurk_cli" }
nix = { version = "0.27.1", features = ["ptrace", "signal"] }
ansi-to-tui = "4.0.1"
console = "0.15.8"
which = "6.0.1"
better-panic = "0.3.0"
tui-big-text = "0.4.2"
chrono = "0.4.38"
bytesize = "1.3.0"
sysinfo = { version = "0.30.12", default-features = false }
webbrowser = "1.0.1"
lddtree = "0.3.4"

[dev-dependencies]
pretty_assertions = "1.4.0"
