[package]
name = "binsider"
version = "0.1.0"
description = "Analyze ELF binaries like a boss"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
ratatui = "0.20.1"
crossterm = "0.26.1"
clap = { version = "4.3.0", features = ["derive", "env", "wrap_help", "cargo"] }
thiserror = "1.0.40"
goblin = "0.6.1"
rust-strings = "0.4.0"

[dev-dependencies]
pretty_assertions = "1.3.0"
